### ISSUE TITLE
Help mounting repo

### ISSUE THREAD

**Issue by w1ll1am23** [DavidKrGH/BackupScripts#1]
Hello, thanks for creating this. Spent last night testing it out and managed to get some data pushed up to Backblaze.

I'm not in the process of trying to reverse the process to make sure I can restore things. I'm struggling to get a repo to mount, not seeing any errors but when running the docker command to mount the repo the resulting mount point doesn't have any data inside.

Command I'm running

docker run --rm \
--name ResticMounted \
--device /dev/fuse --cap-add SYS_ADMIN \
--volume /mnt/user/backups/BackupScripts:/home \
--volume /mnt/user/backups/test:/data \
--volume /mnt/user/backups/restic:/repo \
--volume /mnt/user/backups/test_mount:/mountdir \
--user $(id -u):$(id -g) \
restic/restic \
--password-file=/home/Config/ResticConfig/restic-repo.password \
-r repo mount /mountdir

/restic is the location of my repo I can confirm there is data in there running du -h shows several folders with dozens of mb

I don't get what the /data volume is for? That could be my issue? But I don't see that being called out in the restic documentation just -r repot mount /mountpoint.

Side note, doc on how you are handling restores would be super helpful or maybe even Jobs that can be manually run by the user in case a restore is required. 

Again thanks for this feels like I'm really close to having something but without being able to restore/see the data I'm not confident I"d be able to recover from some data lose.

**Comment by w1ll1am23** [comment]
Update here. So creating a repo on another linux system using restic directly vs docker I'm able to mount that repo. Pulling the repo created on unraid via docker to that same system mounting it I see no data. So something is up with the repo created on unraid. Not sure what though since there is clearly data there in the encrypted state.

**Comment by w1ll1am23** [comment]
Okay update. So pulling the repo back from unraid and loading it up/mounting it on another linux system using restic directly vs with docker I'm able to get to the data. So the backup is working just seems like something with mounting via docker isn't working as expected.

**Comment by w1ll1am23** [comment]
And another update.

Looks like running the mount command on unraid and then opening the console for that docker via unraids docker UI I'm able to access the data there. So something is up with the path mounting or something. Not a big deal though. Seems like everything is working and if needed I could manually restore data. 

Thanks again for this. If you get a chance I'd still love to know what your process would be to restore backups.

**Comment by DavidKrGH** [comment]
Hello @w1ll1am23 

I'm glad you like my repo. Yes you are right, a detailed guide for restoring data is still missing.

> I don't get what the /data volume is for? That could be my issue? But I don't see that being called out in the restic documentation just -r repot mount /mountpoint.

The /data path is there so that you can mount a path in the container that can be used as a destination for your restored data. I usually mount my root directory in the container so that I can restore the data directly to any location.

**Comment by DavidKrGH** [comment]
@w1ll1am23 here is a brief description of what it should look like:

![Screenshot 2023-12-17 155439](https://github.com/DavidKrGH/BackupScripts/assets/86784433/c9245a88-badf-4436-b586-670668bbd9d4)

/mnt/user/appdata/BackupScripts is the directory where the data of the BackupScripts project is located (including my password file)

/mnt/user is the root directory of my user on unraid. This gives the container access to my entire drive so that I can copy data to any location.

/mnt/disks/Backups/AppdataRepo is the directory where my repo is located.

/mnt/disks/Backups/MountDir is an empty folder that I use as a mounting path. The folder must be completely empty for the mounting to work.

If everything has worked, the message appears that the repository is now available under /mountdir.

![Screenshot 2023-12-17 161210](https://github.com/DavidKrGH/BackupScripts/assets/86784433/81a39ade-e4c2-4c0f-8d17-d7141cf72ee6)

In a second terminal window, I now enter the command to dial into the container. It is important that the first terminal window is open all the time. If the first window is closed, the container is also stopped. I can use "ls" to display the data structure of the container. Here you can see the /data path and the /mountdir path. As you can see in the picture, you can navigate through your repo until you reach the snapshot you want to restore. You can now use the Linux copy command to copy an entire snapshot or any part of it to a location in your directory.

I hope this has helped you.

**Comment by w1ll1am23** [comment]
Ahh okay this makes sense. So the restoration would have to happen from inside the container this was the part I was missing. I was thinking once it mounted the mapped path would be accessible from the unraid terminal just my misunderstanding on how docker would expose that path (it doesn't) 

Thanks so much. Working to get all my jobs setup now.
